In [2]:
import pandas as pd
import numpy as np


In [2]:
data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(np.__version__)

1.26.4


In [3]:
a=np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
b=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
c=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [6]:
d=np.array([1, 2, 3], dtype='float')
print(d)

[1. 2. 3.]


In [7]:
e=np.array([1, 2, 3], dtype='bool')
print(e)

[ True  True  True]


In [9]:
np.arange(0, 10, 2)
print(np.arange(0, 10, 2)   .reshape(5, 1))

[[0]
 [2]
 [4]
 [6]
 [8]]


In [ ]:
f=np.array([1, 2, 3], dtype='int')